spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Themedata
    username: morleybread
    password: 2863278679Gy@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /

    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能


#配置静态资源访问器 默认配置就会失效

