spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Person
    username: morleybread
    password: 2863278679Gy@
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能

